function getComputerChoice() {
    let computerNumber = Math.floor(Math.random() * 3) + 1; //Math.floor() + 1 is for rounding up the random decimal values(3 values) generated by Math.random() * 3 

    if (computerNumber === 1) {
        return "rock";
    } else if (computerNumber === 2) {
        return "paper";
    } else {   //else doesn't need any condition
        return "scissors";
    }
}

function getHumanChoice() {
    let userNumber = Number(window.prompt("Enter a number, 1 = Rock , 2 = Paper , 3 = Scissors"));

    if (userNumber === 1) {
        return "rock";
    } else if (userNumber === 2) {
        return "paper";
    } else {
        return "scissors";
    }
}

function playGame() {

    let humanScore = 0;
    let computerScore = 0;

    function playRound(humanChoice, computerChoice) {

        if (humanChoice === "rock" && computerChoice === "paper") {
            console.log("You lose! Paper beats Rock");
            computerScore++;
        } else if (humanChoice === "rock" && computerChoice === "scissors") {
            console.log("You won! Rock beats Scissors");
            humanScore++;
        } else if (humanChoice === "paper" && computerChoice === "rock") {
            console.log("You won! Paper beats Rock");
            humanScore++;
        } else if (humanChoice === "paper" && computerChoice === "scissors") {
            console.log("You lose! Scissor beats Paper");
            computerScore++;
        } else if (humanChoice === "scissors" && computerChoice === "rock") {
            console.log("You lose! Rock beats Scissors");
            computerScore++;
        } else if (humanChoice === "scissors" && computerChoice === "paper") {
            console.log("You Won! Scissors beats Paper");
            humanScore++;
        } else {
            console.log("It's a Tie!")
        }
    }

    for (let i = 0; i < 5; i++) {
        const humanSelection = getHumanChoice();
        const computerSelection = getComputerChoice();
        playRound(humanSelection, computerSelection);
    }

    console.log(`Final score: You - ${humanScore} Computer- ${computerScore}`)

    if (humanScore > computerScore) {
        console.log("Yon won");
    } else if (humanScore < computerScore) {
        console.log("Better luck next Time!");
    } else {
        console.log("It's a tie, Try again!");
    }
}

playGame();